### ISSUE TITLE
Add more details about how to import it into existing project would be helpful

### ISSUE THREAD

**Issue by pengisgood** [ElderByte-/spring-cloud-starter-bootstrap#2]

**Comment by IsNull** [comment]
You simply add it as a dependency. It will be automatically picked up by spring, so there is nothing more to do.

https://bintray.com/elderbyte/maven/spring-cloud-starter-bootstrap/1.5.7.E2

You can see examples for the build settings for Maven, Gradle etc.

**Comment by pengisgood** [comment]
cool, I do use gradle. Thanks.
