### ISSUE TITLE
Put on maven.org?

### ISSUE THREAD

**Issue by karlnicholas** [ElderByte-/spring-cloud-starter-bootstrap#4]
Would be nice to have it on maven.org, otherwise sending an application with this code to the cloud can be a little problematic b/c I will have to either send prebuilt binaries or link in the source or figure out some way to include the .jar file.

**Comment by IsNull** [comment]
While it isnt on maven central, it is on [bintray](https://bintray.com/elderbyte/maven/spring-cloud-starter-bootstrap).

You only have to add the repo in your pom:
```xml
<repository>
    <snapshots>
        <enabled>false</enabled>
    </snapshots>
    <id>bintray-elderbyte-maven</id>
    <name>bintray</name>
    <url>https://dl.bintray.com/elderbyte/maven</url>
</repository>
```

Then it will work with the dependency:

```xml
<dependency>
  <groupId>com.elderbyte.spring.cloud</groupId>
  <artifactId>spring-cloud-starter-bootstrap</artifactId>
  <version>2.0.1.E12</version>
  <type>pom</type>
</dependency>
```

**Comment by karlnicholas** [comment]
Thanks, I was just finding that out and looking for the magic repository incantation. It should work.
