### ISSUE TITLE
Spring Boot 2.0 support with Java 8

### ISSUE THREAD

**Issue by karlnicholas** [ElderByte-/spring-cloud-starter-bootstrap#5]
I'm on Java 8 using Springboot 2.0 and when I bring in any of the 2.0 version of spring-cloud-start-bootstrap it says the byte code is version 53 (8 is 52), so I'm assuming that's Java 9. Any chance we can get it compiled and released for Java 8 since that would be compatible with spring-boot 2 java requirements?

PS> I tried 1.5.6 version and it compiles but I am getting a runtime failure looking for various Netflix classes (com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect, org.springframework.cloud.netflix.feign.FeignFormatterRegistrar). I'm not experienced enough with these packages to know if there are dependency issues or version issues.

**Comment by IsNull** [comment]
The library is actually on Java 10 by now 😄
We tend to use cutting edge features and therefore follow the latest dependency and framework versions closely - same for Java. I tried to cross-compile from Java 10 Source to Java 8, but it did not work. So I fear this library will require Java 10.

`I tried 1.5.6 version` You can not mix Spring 1.x with 2.x, there are a lot of dependency miss-matches.

Why not upgrade your app to Java 10? Should not cause too much issues - upgrading from Spring 1.5 to 2.0 was much more painful if I remember correctly.

**Comment by karlnicholas** [comment]
Yea, I was just noticing the `var` stuff. I don't want to update to Java 10 because in a larger enterprise it's not possible to do that for a while. I'm just looking for the Feign Pageable stuff, so I'll just copy the files I need into the project. Thanks.

**Comment by IsNull** [comment]
>I don't want to update to Java 10 because in a larger enterprise it's not possible to do that for a while.

If you run your java apps in docker containers, each app can use the JDK it wants to / needs to. Otherwise, we would live in a JRE hell aswell...

> I'm just looking for the Feign Pageable stuff, so I'll just copy the files I need into the project.

Yes I figured as much - its quite a small library ^^

**Comment by karlnicholas** [comment]
> If you run your java apps in docker containers, each app can use the JDK it wants to / needs to. Otherwise, we would live in a JRE hell aswell...

Yes, very good point, though in enterprise even that can be controlled.
